repos: 
  - repo : local
    hooks :
      - id : run_checkstyle
        name : Check 1
        description : Checking first file
        entry : python3 precommit_checks/check1.py
        language : python